-- ============================================================
--  个人主页 · 对话记录表（Supabase / PostgreSQL）
-- ============================================================
--  用途：把访客与「数字分身」的每一轮问答存下来，便于在后台（Supabase
--        控制台 → Table Editor → dialog）回看访客都在问什么。
--
--  隐私约定：**不记录 IP、不记录浏览器指纹、不记录联系方式**，只存
--            「访客问的这句话 + 分身的回答」以及页面地址和会话标识，
--            会话标识是浏览器随机生成的一段字符串，不指向具体个人。
--
--  使用方法：
--    1. 打开 Supabase 控制台 → 左侧 SQL Editor → New query
--    2. 把本文件全部内容粘贴进去 → 点 Run
--    3. 看到 "Success. No rows returned" 即建表成功
--    （也可以让脚本用 Management API 直接执行，见 docs/05 §4.3）
-- ============================================================

-- ---------- 1. 建表 ----------
create table if not exists public.dialog (
  id          bigint generated by default as identity primary key,
  session_id  text,                                  -- 访客会话标识（浏览器随机生成，用于把同一人的多轮串起来）
  page_url    text,                                  -- 提问时所在页面
  question    text not null,                         -- 访客问的话
  answer      text not null,                         -- 数字分身的回答
  model       text,                                  -- 回答用的模型名（便于对比换模型前后的效果）
  latency_ms  integer,                               -- 本次回答耗时（毫秒）
  source      text,                                  -- 来源：supabase-edge-function / local-backend
  created_at  timestamptz not null default current_timestamp
);

-- ---------- 2. 索引：按时间倒序查看 / 按会话串起多轮 ----------
create index if not exists dialog_created_at_idx
  on public.dialog (created_at desc);

create index if not exists dialog_session_id_idx
  on public.dialog (session_id);

-- ---------- 3. 字段长度保护（数据库层兜底，服务端也会截断）----------
alter table public.dialog drop constraint if exists dialog_question_len;
alter table public.dialog
  add constraint dialog_question_len
  check (char_length(question) between 1 and 4000);

alter table public.dialog drop constraint if exists dialog_answer_len;
alter table public.dialog
  add constraint dialog_answer_len
  check (char_length(answer) between 1 and 8000);

alter table public.dialog drop constraint if exists dialog_session_len;
alter table public.dialog
  add constraint dialog_session_len
  check (session_id is null or char_length(session_id) <= 64);

alter table public.dialog drop constraint if exists dialog_page_url_len;
alter table public.dialog
  add constraint dialog_page_url_len
  check (page_url is null or char_length(page_url) <= 500);

-- ---------- 4. 行级安全（RLS）----------
-- 开启后默认拒绝一切匿名访问，必须显式放行。
alter table public.dialog enable row level security;

-- 只放行「匿名插入」，**不放行读取**：这样即使前端密钥泄露，
-- 别人也只能往里写，读不到访客和分身的对话内容（读取只发生在控制台/服务端）。
drop policy if exists "anon can insert dialog" on public.dialog;
create policy "anon can insert dialog"
  on public.dialog
  for insert
  to anon
  with check (true);

-- 显式授权：保证 anon 角色能访问该表（配合上面的策略才真正生效）
grant usage on schema public to anon;
grant insert on public.dialog to anon;

-- ---------- 5. 自检 ----------
-- 执行完可运行下面几句确认表与策略都已就位：
--   select tablename, rowsecurity from pg_tables where tablename = 'dialog';
--   select policyname, cmd, roles from pg_policies where tablename = 'dialog';
--   select count(*) from public.dialog;
--
-- 常用查询（控制台里直接跑）：
--   -- 最近 50 轮对话
--   select created_at, session_id, question, answer from public.dialog
--     order by created_at desc limit 50;
--   -- 大家最常问什么（简单聚一下前缀）
--   select left(question, 20) as q, count(*) from public.dialog
--     group by 1 order by 2 desc limit 20;
--   -- 某一次访问的完整对话
--   select created_at, question, answer from public.dialog
--     where session_id = '把上面的会话 ID 粘这里' order by created_at;
