-- ============================================================
--  个人主页 · 意见反馈表（Supabase / PostgreSQL）
-- ============================================================
--  使用方法：
--    1. 打开 Supabase 控制台 → 左侧 SQL Editor → New query
--    2. 把本文件全部内容粘贴进去 → 点 Run
--    3. 看到 "Success. No rows returned" 即建表成功
-- ============================================================

-- ---------- 1. 建表 ----------
create table if not exists public.feedback (
  id          bigint generated by default as identity primary key,
  nickname    text,                                  -- 称呼（选填）
  contact     text,                                  -- 联系方式（选填）
  category    text not null default '其他',          -- 反馈类型
  message     text not null,                         -- 反馈内容
  page_url    text,                                  -- 提交页面
  user_agent  text,                                  -- 浏览器标识
  created_at  timestamptz not null default current_timestamp
);

-- ---------- 2. 索引：按时间倒序查看 ----------
create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);

-- ---------- 3. 字段长度保护（数据库层兜底，服务端也会校验）----------
alter table public.feedback drop constraint if exists feedback_message_len;
alter table public.feedback
  add constraint feedback_message_len
  check (char_length(message) between 1 and 2000);

alter table public.feedback drop constraint if exists feedback_nickname_len;
alter table public.feedback
  add constraint feedback_nickname_len
  check (nickname is null or char_length(nickname) <= 50);

alter table public.feedback drop constraint if exists feedback_contact_len;
alter table public.feedback
  add constraint feedback_contact_len
  check (contact is null or char_length(contact) <= 120);

alter table public.feedback drop constraint if exists feedback_category_len;
alter table public.feedback
  add constraint feedback_category_len
  check (category is null or char_length(category) <= 20);

-- ---------- 4. 行级安全（RLS）----------
-- 开启后默认拒绝一切匿名访问，必须显式放行。
alter table public.feedback enable row level security;

-- 只放行「匿名插入」，不放行读取/修改/删除。
-- 这样即使前端密钥泄露，别人也只能往里写，看不到你收到的反馈内容。
drop policy if exists "anon can insert feedback" on public.feedback;
create policy "anon can insert feedback"
  on public.feedback
  for insert
  to anon
  with check (true);

-- 显式授权：保证 anon 角色能访问该表（配合上面的策略才真正生效）
grant usage on schema public to anon;
grant insert on public.feedback to anon;

-- ---------- 5. 自检 ----------
-- 执行完可运行下面这句确认表与策略都已就位：
--   select tablename, rowsecurity from pg_tables where tablename = 'feedback';
--   select policyname, cmd, roles from pg_policies where tablename = 'feedback';
